### ISSUE TITLE
Html before Suspense boundary partially streamed 

### ISSUE THREAD

**Issue by albertogasparin** [Ephem/react#23]
It looks like react-dom streamer splits the output into chunks of 14Kb. However that chunking is taken into account even when Suspense is being used, which means that the output might be truncated way before the Suspense boundary and the user might see a section of the page half rendered.

I tried to track down when this happens and it looks like when `ReactDOMServerRendererAsync.readAsync` is called, if it finds a `REACT_SUSPENSE_TYPE` frame then it sets the Suspense promise as second index of the current queue, later picked up by `flattenAndResolveQueue` which awaits for it.
The problem is that the queue might contain other html data that is hold until the Suspense promise is resolved, potentially leaving the user with a half streamed component.
We should flush all the queue html before awaiting for the suspense promise (quickly tried but couldn't make it work).

**Comment by Ephem** [comment]
Another great find, thanks for reporting it!

There are a few things involved here:

* The queue you mentioned
* Node streams - number of bytes to read and `highWaterMark` (defaults to 16kb, could make this configurable)
* Browser behaviour (most only output chunks larger than 4kb to the DOM)

I'm pretty sure the queue is working as intended and that this problem is related to `highWaterMark` and the interaction between the readable and writeable streams. I'm not proficient enough in node streams to have a solution right off the bat, so I will need to investigate deeper.

Related, [here are some tests](https://github.com/Ephem/react-lightyear/blob/4e31b3abb62d5f7806a29491333b083eec693df4/packages/react-dom/src/__tests__/ReactServerRenderingSuspense-test.js#L375) that explicitly set `highWaterMark` to 1 to be able to test this.

**Comment by albertogasparin** [comment]
Well, I'm no stream expert either, but while tinkering around with the code I was able to have it stream the smaller remaining chunk before the suspension (it was probably a couple of kb). However was doing it in away that was breaking the rest of the stream...

What I did might not make sense but basically: in `flattenAndResolveQueue` if `queue[0][1].then` condition was true, I was first calling the callback `cb` with `result = queue[0][0]` and then adding the other callback to `then`.
This way the stuff already in the queue was actually sent through regardless of the size, however I was no longer getting the rest of the content 😅

**Comment by Ephem** [comment]
Hmm, maybe the queue is at fault after all then. I thought I'd implemented it in a way that it would flush `[0][0]` entirely when waiting for a promise, but maybe I dreamt or didn't verify that part. :) I'll investigate! Thanks for expanding on the issue.

**Comment by Ephem** [comment]
Real life got hectic so took some time to get around to this. I had indeed dreamt that I implemented the early flushing part on suspends but this should be fixed now. Thanks again for reporting it! :)

Update: This is now out in `0.2.4` if you want to try it out.
